### ISSUE TITLE
dis.SetDataPdu Usage

### ISSUE THREAD

**Issue by dragsu** [open-dis/DISWebGateway#4]
Any chance you can provide an example of using dis.SetDataPdu with some variable data records.

**Comment by leif81** [comment]
Does this unit test help?

https://github.com/open-dis/open-dis-java/blob/master/src/test/java/edu/nps/moves/dis/SetDataPduTest.java

**Comment by dragsu** [comment]
Sorry I was looking at https://github.com/open-dis/DISWebGateway. Trying to use dis.SetDataPdu in dis.js to create a SetData pdu with a single variable data field with some text. Currently, I'm doing the below but Wireshark is not showing the variable message right.

```
var setDpdu = new dis.SetDataPdu();
setDpdu.numberOfVariableDatumRecords = 1;
var anX = new dis.VariableDatum();
anX.variableDatumID = 2;
anX.variableDatumLength = 32;

var charA = new dis.OneByteChunk();
charA.otherParameters[0]='t';
var charB = new dis.OneByteChunk();
charB.otherParameters[0]='e';
var charC = new dis.OneByteChunk();
charC.otherParameters[0]='s';
var charD = new dis.OneByteChunk();
charD.otherParameters[0]='t';

anX.variableData[0] = charA;
anX.variableData[1] = charB;
anX.variableData[2] = charC;
anX.variableData[3] = charD;

setDpdu.variableDatums.push(anX);
```

**Comment by leif81** [comment]
What you're doing there seems reasonable...

I have this recollection that Wireshark doesn't display the variable data field properly. But it's been a while since I've done this so maybe I'm thinking about something else. Do you have a way to confirm if the issue is with Wireshark or your code?

**Comment by leif81** [comment]
If it helps, here's a sample SetData pdu raw packet and the variable data contained in it should read "allunits".

https://github.com/open-dis/open-dis-java/blob/master/src/test/resources/edu/nps/moves/dis/SetDataPdu-vbs-script-cmd.raw

**Comment by quonn77** [comment]
How to use in C++?

**Comment by leif81** [comment]
> How to use in C++?

@quonn77 I had a chance to reply to your question over in the cpp repository. Hopefully it helps somewhat. I'll link to that issue and thread here and we can continue a conversation over there. https://github.com/open-dis/open-dis-cpp/issues/71

**Comment by quonn77** [comment]
@leif81 Yes I agree
